version: '3.7'
services:
  db:
    image: postgres:14.2-alpine
    container_name: blind_dates_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: blind_dates
      POSTGRES_USER: blind_dates
      POSTGRES_PASSWORD: blind_dates
    ports:
      - "5432:5432"
  app:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      POSTGRES_DB: blind_dates
      POSTGRES_USER: blind_dates
      POSTGRES_PASSWORD: blind_dates
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}
networks:
  default:
    name: blind_dates_default
